# Generated by Django 5.2.13 on 2026-09-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userrole'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrole',
            table='user_roles',
        ),
    ]
