# Generated by Django 5.2.13 on 2026-09-20 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_userrole_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='authentication.module')),
            ],
            options={
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='UserRolePermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='authentication.feature')),
                ('userRole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='authentication.userrole')),
            ],
            options={
                'db_table': 'user_role_permissions',
            },
        ),
    ]
