# Generated by Django 5.2.13 on 2026-09-25 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_module_feature_userrolepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='authentication.module'),
        ),
        migrations.AlterField(
            model_name='userrolepermission',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='authentication.feature'),
        ),
        migrations.AlterField(
            model_name='userrolepermission',
            name='userRole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='authentication.userrole'),
        ),
    ]
