# Generated by Django 5.2.13 on 2026-09-20 06:13

import features.shared.helpers.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_document_restore_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, storage=features.shared.helpers.storage.UnicodePreservingStorage(), upload_to='documents/'),
        ),
    ]
