# Generated by Django 5.2.13 on 2026-09-20 06:13

import features.shared.helpers.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=features.shared.helpers.storage.UnicodePreservingStorage(), upload_to='chatbot/'),
        ),
    ]
